version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tubesync-tubesync1
      APP_PORT: 3000
    
  server:
    image: ghcr.io/meeb/tubesync:latest
    user: "1000:1000"
    init: true
    volumes:
      - /umbrel/tubesync/tubesync-config:/config
      - /umbrel/tubesync/tubesync-downloads:/downloads
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
